[mypy]
python_version = 3.12
files = app
warn_unused_configs = True
warn_redundant_casts = True
warn_unused_ignores = True
check_untyped_defs = True
no_implicit_optional = True

[mypy-langchain_community.*]
ignore_missing_imports = True

[mypy-langchain_core.*]
ignore_missing_imports = True

[mypy-prometheus_client.*]
ignore_missing_imports = True
