apiVersion: v1
kind: LimitRange
metadata:
  name: medical-rag-limit-range
  namespace: medical-rag
spec:
  limits:
    - type: Container
      default:
        cpu: "1"
        memory: 2Gi
      defaultRequest:
        cpu: 250m
        memory: 512Mi
      max:
        cpu: "2"
        memory: 4Gi
      min:
        cpu: 100m
        memory: 128Mi
