apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: medical-rag-network-policy
  namespace: medical-rag
spec:
  podSelector:
    matchLabels:
      app: medical-rag-chatbot
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 5000
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 53
        - protocol: UDP
          port: 53
